### ISSUE TITLE
在安卓平板上使用这个zsh一键配置脚本报错

### ISSUE THREAD

**Issue by Droid-MAX** [Cabbagec/termux-ohmyzsh#1]

**Comment by Droid-MAX** [comment]
$HOME/.oh-my-zsh/oh-my-zsh.sh:31: no matches found: $HOME/.oh-my-zsh/lib/*.zsh

**Comment by Droid-MAX** [comment]
https://github.com/4679/oh-my-termux
用他的也是这样
装好重启Termux后就报这样的错误

**Comment by Cabbagec** [comment]
@Droid-MAX 
原因是这个 `$HOME/.oh-my-zsh/lib` 目录下缺 zsh 配置文件。应该是你之前安装的时候手动中断过，又重新安装了一遍。
可以删除 `rm -fr $HOME/.oh-my-zsh`，然后：
```
git clone https://github.com/robbyrussell/oh-my-zsh $HOME/.oh-my-zsh --depth 1
```
再重开 Termux

**Comment by Droid-MAX** [comment]
并不是你说的这个原因，我重装Termux多次按照说明当中的步骤来安装也不行，重启Termux后都会有$HOME/.oh-my-zsh/oh-my-zsh.sh:31: no matches found: $HOME/.oh-my-zsh/lib/*.zsh这样的提示，且蓝条条的命令提示符没有显示出来

**Comment by Cabbagec** [comment]
看下你的 `~/.oh-my-zsh/lib` 目录下都有哪些文件呢？应该都是类似 `*.zsh` 这种，问题很明显是缺少这些文件导致 `oh-my-zsh.sh` 没有正常执行，这样就没办法读入各种变量了。正常步骤的话不应该缺少这些文件的啊🤔

**Comment by truc0** [comment]
我也是同样的情况。
系统：
设备名称： 小米平板2
系统版本：
```
Linux localhost 3.14.37-x86_64-g172c52b #1 SMP PREEMPT Mon Jul 2 17:18:37 CST 2018 x86_64 Android
```
错误信息：
```
/data/data/com.termux/files/home/.oh-my-zsh/oh-my-zsh.sh:34: no matches found: /data/data/com.termux/files/home/.oh-my-zsh/lib/*.zsh
.zshrc:source:101: no such file or directory: /home/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
```
安装方法： CURL 安装

其他：    
已经检查过`.oh-my-zsh/lib`里面的文件齐全，`/home/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh`文件也在

在命令前面显示的是`%`而不是蓝色标签

尝试过一下方法：

```
chmod +x -R .oh-my-zsh
```

**Comment by Cabbagec** [comment]
@wozuishuai13768 有一点疑问，你上边提到 `/home/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh` 这个目录，你的意思是 `$HOME/.zsh-syntax-highlighting...` 吗？普通平板 Android 系统正常情况下没有 `/home` 目录的，并且 Termux 也只有它本身数据目录的权限。
