### ISSUE TITLE
颜色选项只有一个了

### ISSUE THREAD

**Issue by wanqx** [Cabbagec/termux-ohmyzsh#14]
u0_a198@localhost  ~  chcolor
The default color theme is Tango.
You can choose another one from the list below
(0) vag.colors
Enter a number, leave blank to not to change:0

**Comment by wanqx** [comment]
I have the same problem!!!

**Comment by ridwanirawan** [comment]
Yes please fix it

**Comment by Cabbagec** [comment]
Sorry for the delay, but I'm not able to reproduce this issue by any means on my device, I cannot actually do any debug stuff. 

So anyone here has this problem on your termux, you can try removing the double quotes around the variable `COLORS_DIR` in `~/.termux/colors.sh`, see patch #17 . 

If you have any idea why this issue should occur, feel free to leave your comments. I will try to fix it.
