### ISSUE TITLE
Tips to fix only a vag color on ohmyzsh on termux

### ISSUE THREAD

**Issue by ridwanirawan** [Cabbagec/termux-ohmyzsh#16]
Step.
1. mkdir colors
2. cd ~/.termux/colors
3. mv * ~/colors
4. cd ~/.colors
5. select color that you want
6. cp ~/.termux/colors
7. chcolor then 0
8. Color is changed

it must be 1 color on ~/.termux/colors directory no more

**Comment by yusufqq** [comment]
А как поставить стандартный шрифт и цвет termux ??? Подскажите пожалуйста

**Comment by Cabbagec** [comment]
see fed2ebc
