### ISSUE TITLE
Errors at startup

### ISSUE THREAD

**Issue by brainfucker-rwx** [Cabbagec/termux-ohmyzsh#18]
![image](https://user-images.githubusercontent.com/54035900/64046502-6bbabd80-cb85-11e9-9e8d-22a8372bec87.png)
I installed Termux, installed zsh according to the instructions. These errors come out

**Comment by Cabbagec** [comment]
This may due to broken oh-my-zsh plugin on previous versions, try run `upgrade_oh_my_termux` then restart.
