### ISSUE TITLE
[Feature]建议加入FiraCode字体

### ISSUE THREAD

**Issue by diyhome** [Cabbagec/termux-ohmyzsh#19]
这个字体用着挺喜欢的,附上Github链接:[FiraCode](https://github.com/tonsky/FiraCode)

**Comment by Cabbagec** [comment]
好的！感谢关注，待测试验证没问题后我会加上

**Comment by Cabbagec** [comment]
FiraCode 字体已加入 2ec9e192754178ceb2dc97cebd205751c7b336c1
