### ISSUE TITLE
Помощь как поставить стандартные цвета и шрифта от termux

### ISSUE THREAD

**Issue by yusufqq** [Cabbagec/termux-ohmyzsh#23]
Удалять я не хочу у меня много полезных скриптов!!! Помогите

**Comment by Cabbagec** [comment]
Try ```cp -fr ~/.termux/colors/[the-color-scheme-you-want].colors ~/.termux/colors.properties```
then restart termux. The command above should work, the automated shell script does the same thing anyway.

Some people did report that that shell script was broken on their device, but I've tested on all my devices and failed to reproduce the bug. Maybe I shouldn't touch anything that works for most people. So for anyone encounters any problem with respect to color theme, you can use the command above instead.
