### ISSUE TITLE
How to delete this from termux 

### ISSUE THREAD

**Issue by gurugrover** [Cabbagec/termux-ohmyzsh#26]

**Comment by Cabbagec** [comment]
## Revert environment
1. Under the home directory, you can find some zshrc backup files named with date, like `.zshrc.bak.2018.1.1-00:00:00`. Rename the backup file back to `.zshrc`. If there doesn't exist any backups, remove the current `.zshrc`.

2. You can also find some termux configuration backup directory, named with date, like `.termux.bak.2018.1.1-00:00:00`. Rename the backup directory back to `.termux`. If there doesn't exist any backups, remove the current `.termux`.

3. Restart termux
