### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by thiagomlouco1** [Cabbagec/termux-ohmyzsh#3]
How to uninstall and return to the original ?

**Comment by Cabbagec** [comment]
@thiagomlouco1  You can just clear out the `.termux` directory under the home. Or `rm $HOME/.termux/* -fr`

**Comment by Cristishor201** [comment]
> @thiagomlouco1 You can just clear out the `.termux` directory under the home. Or `rm $HOME/.termux/* -fr`

removed dir-s didn't worked. I needed to uninstall Termux, and install it all packages again !

**Comment by user8873** [comment]
Hi,my congratulations.  After installation I can't save my banner and username. How to save and install termux-ohmyzsh ?  thanks

**Comment by user8873** [comment]
@Cabbagec Hi,my congratulations. 
 After installation I can't save my banner and username. 
How to save and install termux-ohmyzsh ?  
thanks.

**Comment by Cabbagec** [comment]
@user8873 After installation, grab files from one of your old `.termux.bak.2022...` backups directory under `$HOME`, copy and overwrite into your `.termux` directory, except for `font.ttf` and `colors.properties`.

**Comment by user8873** [comment]
Thank you

З повагою Ігор Юрійович

                      ☯︎࿊☯︎

𝐒𝐢𝐧𝐜𝐞𝐫𝐞𝐥𝐲 𝐰𝐢𝐭𝐡 𝐲𝐨𝐮 𝐈𝐠𝐨𝐫 𝐘𝐮𝐫𝐢𝐞𝐯𝐢𝐜𝐡
𝐑𝐄𝐒𝐏𝐄𝐂𝐓 𝐓𝐎 𝐅𝐀𝐈𝐑 𝐏𝐋𝐀𝐘



чт, 25 серп. 2022, 06:25 користувач Brandon ***@***.***> пише:

**Comment by hanifonbd** [comment]
Is it possible to uninstall Cabbagec / Termux-ohmyzsh ?
