### ISSUE TITLE
Theme for Termux

### ISSUE THREAD

**Issue by Turtle-hash** [Cabbagec/termux-ohmyzsh#32]

**Comment by Cabbagec** [comment]
What's the problem you are experiencing? Mind share some details with me in this issue?

**Comment by Turtle-hash** [comment]
Sorry for the thread, I am new to Git, just thought it as bookmark", didn't
know that it will turn into a negative issue, I have already uninstalled
Git, if this is not a big deal, then forgive me for that issue.

**Comment by Cabbagec** [comment]
Don't worry, that's fine. Issues are means to help improve projects, and are always welcomed. Have a nice day!
