### ISSUE TITLE
nodejs程序可能会有问题

### ISSUE THREAD

**Issue by iuxt** [Cabbagec/termux-ohmyzsh#33]
pkg install nodejs npm
npm install -g hexo-cli

再运行hexo命令时会报错, 但是bash就不会

**Comment by Cabbagec** [comment]
我尝试安装执行了 `hexo`，发现提示 `bad interpreter: /usr/bin/env`。这是因为 `termux` 环境的路径有个 prefix，`termux` 中的 `env` 位于 `/data/data/com.termux/files/usr/bin/env`，而不是 `/usr/bin/env`。你可以用 `which env` 看到这个绝对路径。`termux` 自带了修复这种 shebang 问题的脚本，你可以尝试用 `termux-fix-shebang $(which hexo)` 解决这个问题。执行这个命令后我的 `termux` 可以正常运行 `hexo`。

**Comment by Cabbagec** [comment]
如果不是 shebang 的问题，你是否愿意在这个 issue 里跟我分享具体的错误细节呢？谢谢！
