### ISSUE TITLE
Change themes 

### ISSUE THREAD

**Issue by asterisk-ragavan** [Cabbagec/termux-ohmyzsh#34]
How can I change themes, pls anyone help

**Comment by Cabbagec** [comment]
Once you've done installation, restart termux app then try to run `chcolor` to change color schemes, or `chfont` to change font. To change oh-my-zsh shell theme, try `omz list themes` to list all available ones, and try `omz use <theme>` to apply one.

**Comment by asterisk-ragavan** [comment]
tqsm lame try

**Comment by asterisk-ragavan** [comment]
tqsm lame try

**Comment by asterisk-ragavan** [comment]
> Once you've done installation, restart termux app then try to run `chcolor` to change color schemes, or `chfont` to change font. To change oh-my-zsh shell theme, try `omz list themes` to list all available ones, and try `omz use <theme>` to apply one.

![Screenshot_20210412-212752_Termux.png](https://user-images.githubusercontent.com/75389172/114424638-f3780300-9bd5-11eb-9d04-a07c64e9baa7.png)

Iam getting like this not able to apply theme

**Comment by Cabbagec** [comment]
:thinking: Should've checked the helping output on your screenshot. I didn't remember the commands exactly though. `omz theme use <name>` way to go, I guess. Or change the `ZSH_THEME` variable in your `#HOME/.zshrc` if you want to use your theme persistently.
