### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by davywong** [Cabbagec/termux-ohmyzsh#43]
Hello. I got an issue when I did an "omz update", hints as follows:
Updating Oh My Zsh
fatal: remote error:
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.

This seemed a protocol error resulted from github, I tried reinstalling termux-ohmyzsh, but the fatal stayed there.

**Comment by CatEricka** [comment]
Workaround:

cd `~/oh-my-zsh` and run command `git remote set-url origin "https://github.com/ohmyzsh/ohmyzsh.git"`

**update**: cd `~/.oh-my-zsh`

**Comment by davywong** [comment]
Thx for reply. 
Actually I'm using termux-ohmyzsh, there's no `~/oh-my-zsh` dir, do you mean `~/termux-ohmyzsh`?
Yet I checked up the remote repo using `git remote -v` to find out the "https" been applied. 
`origin https://github.com/Cabbagec/termux-ohmyzsh.git (fetch)`
`origin https://github.com/Cabbagec/termux-ohmyzsh.git (push)`

> Workaround:
> 
> cd `~/oh-my-zsh` and run command `git remote set-url origin "https://github.com/ohmyzsh/ohmyzsh.git"`

**Comment by CatEricka** [comment]
https://github.com/Cabbagec/termux-ohmyzsh/blob/ed650a2e2bbf70e895d926d7eb3961860d6e2145/install.sh#L11

It's `~/.oh-my-zsh` not `~/oh-my-zsh`, I missed a period.

**Comment by davywong** [comment]
Yeah. Thx a million. That works. 
I don't know why I manually modified the termux-ohmyzhs/install.sh file from "git" to "https", but that didn't seem to work at first.

**Comment by CatEricka** [comment]
see also #44

**Comment by CatEricka** [comment]
> Yeah. Thx a million. That works. I don't know why I manually modified the termux-ohmyzhs/install.sh file from "git" to "https", but that didn't seem to work at first.

If you modified `install.sh`, you will need to run `install.sh` to reinstall termux-ohmyzsh for it to take effect, which is equivalent to modifying git remote repo directly
