### ISSUE TITLE
命令问题

### ISSUE THREAD

**Issue by Snowfly-Guo** [Cabbagec/termux-ohmyzsh#47]
执行sh -c这个命令之后没有让我选择字体和颜色的选项 我该怎么做？![Screenshot_20220609_211050.jpg](https://user-images.githubusercontent.com/79904577/172855095-cf7bc17f-f241-412f-9904-4c123d1ab261.jpg)

**Comment by Cabbagec** [comment]
执行完安装如果没有错误，`chfont` 可以更改字体，`chcolor` 更改颜色

**Comment by Snowfly-Guo** [comment]
> 执行完安装如果没有错误，`chfont` 可以更改字体，`chcolor` 更改颜色

好的
