### ISSUE TITLE
permission denied: dircolors

### ISSUE THREAD

**Issue by jyuan15** [Cabbagec/termux-ohmyzsh#7]
本来好好的，今天打开termux就出现提示：
~/.oh-my-zsh/lib/theme-and-appearance.zsh: 32: permission denied: dircolors，

本来想卸载重装，但不知怎么卸载，把相关的所有文件全删了，重装后打开没有显示默认主题（也就是说没有生效，可能文件未完全删除）。
请问该如何解决？谢谢

**Comment by Cabbagec** [comment]
应该只是个小问题。如果重装整个 termux 的话，所有已经安装软件包和各种环境都会被清除，非常不建议这样做。只把 oh-my-zsh 环境删了重来无所谓，但在这之前还是建议你先试试运行 `upgrade_oh_my_zsh` 更新 oh-my-zsh 环境，如果重开 termux 还是不行那就：
1. `rm -rf ~/.zshrc ~/.oh-my-zsh`
2. 退出 termux 重开
3. `git clone git://github.com/robbyrussell/oh-my-zsh.git $HOME/.oh-my-zsh --depth 1`
4. `cp $HOME/.oh-my-zsh/templates/zshrc.zsh-template $HOME/.zshrc`
5. 退出 termux 重开

**Comment by jyuan15** [comment]
谢谢回答，我在帖子中说的“卸载”就是指卸载termux-ohmyzsh，但不知如何卸载。

前几天出问题后，已经把Termux删掉重装了，oh-my-zsh当然也正常了。如再出现上述现象，再用你的方法来处理。
另外，我改过某些主题，好像就不能在线更新oh-my-zsh了。

**Comment by chai1992** [comment]
เมื่อ 18 พ.ค. 2018 11:05 AM "Brandon" <notifications@github.com> เขียนว่า
