### ISSUE TITLE
[oh-my-zsh] Insecure completion-dependent directories detected

### ISSUE THREAD

**Issue by jyuan15** [Cabbagec/termux-ohmyzsh#8]
今天重装出现以下错误：

[oh-my-zsh] Insecure completion-dependent directories detected:
drwx------   11 u0_a314  u0_a314       4096 May 24 07:02 /data/data/com.termux/files/home/.oh-my-zsh
drwx------  243 u0_a314  u0_a314       4096 May 24 07:02 /data/data/com.termux/files/home/.oh-my-zsh/plugins
drwx------    2 u0_a314  u0_a314       4096 May 24 07:02 /data/data/com.termux/files/home/.oh-my-zsh/plugins/git
drwx------    3 u0_a314  u0_a314       4096 May 24 07:02 /data/data/com.termux/files/usr/share/zsh
drwx------    4 u0_a314  u0_a314       4096 May 24 07:02 /data/data/com.termux/files/usr/share/zsh/5.5.1
drwx------    2 u0_a314  u0_a314      32768 May 24 07:02 /data/data/com.termux/files/usr/share/zsh/5.5.1/functions
-rwx------    1 u0_a314  u0_a314        279 Apr 23 03:42 /data/data/com.termux/files/usr/share/zsh/5.5.1/functions/_SUSEconfig
-rwx------    1 u0_a314  u0_a314       2800 Apr 23 03:42 /data/data/com.termux/files/usr/share/zsh/5.5.1/functions/_a2ps
-rwx------    1 u0_a314  u0_a314        490 Apr 23 03:42 /data/data/com.termux/files/usr/share/zsh/5.5.1/functions/_a2utils
-rwx------    1 u0_a314  u0_a314       2638 Apr 23 03:42 /data/data/com.termux/files/usr/share/zsh/5.5.1/functions/_aap
-rwx------    1 u0_a314  u0_a314       1022 Apr 23 03:42 /data/data/com.termux/files/usr/share/zsh/5.5.1/functions/_absolute_command_paths
.......
[oh-my-zsh] For safety, completions will be disabled until you manually fix all
[oh-my-zsh] insecure directory permissions and ownership and restart oh-my-zsh.
[oh-my-zsh] See the above list for directories with group or other writability.

[oh-my-zsh] Insecure completion caches also detected:
-rw-------    1 u0_a314  u0_a314      44055 May 24 07:32 /data/data/com.termux/files/home/.zcompdump-localhost-5.5.1
[oh-my-zsh] Moving to "/data/data/com.termux/files/home/.oh-my-zsh/cache/zcompdump-bad/"...

No command 'compdef' found, did you mean:
 Command 'compare' from package 'imagemagick'
No command 'compdef' found, did you mean:
 Command 'compare' from package 'imagemagick'
No command 'compdef' found, did you mean:
 Command 'compare' from package 'imagemagick'
No command 'compdef' found, did you mean:
 Command 'compare' from package 'imagemagick'
......

去oh-my-zsh 项目看了下，好像是oh-my-zsh更新引起的bug，但它Issue里面的解决方法是pc端的，不知在安卓上如何解决？谢谢～

**Comment by Cabbagec** [comment]
这大概只是权限问题，运行 `whoami` 或者 `id` 看下目前的用户是？是否因为某种原因改变了用户？

**Comment by Cabbagec** [comment]
@jyuan15 你暂时可以先把 `ZSH_DISABLE_COMPFIX=true` 加到 `~/.zshrc` 的第一行再重开 Termux，但可能会有其他问题

**Comment by jyuan15** [comment]
@Cabbagec 加了`ZSH_DISABLE_COMPFIX=true`后不再出现权限提示了，但有些主题的图标不能正常显示，比如dpoggi主题，稳定版和开发版的图标是不一样的（闪电和圆圈），而现在都显示为同样图标。

另外，查看当前用户，发现每重装一次，用户uid都会变大，现在是10325，之前是10314，再之前是10309，不知这是否正常？

**Comment by Cabbagec** [comment]
@jyuan15 图标的问题似乎是字体引起的，我这看看能不能给字体打上补丁。uid 是正常的。

**Comment by jyuan15** [comment]
@Cabbagec 谢谢~
